apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    test: infr030
spec:
  containers:
  - name: nginx
    image: nginx:1.28
    env:
    - name: MA_VAR_ENV
      value: "toto"
    - name: MY_PASSWORD
      valueFrom:
        secretKeyRef:
          name: password
          key: password
    ports:
    - containerPort: 80
    securityContext:
      allowPrivilegeEscalation: true