apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    test: infr030
spec:
  containers:
  - name: nginx
    image: nginx:1.28
    volumeMounts:
      - name: index
        mountPath: "/usr/share/nginx/html"
        readOnly: true
    ports:
    - containerPort: 80
    securityContext:
      allowPrivilegeEscalation: true
  volumes:
  - name: index
    configMap:
      name: index-cm