apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    test: infr030
spec:
  containers:
  - name: nginx
    image: nginx:1.28
    ports:
    - containerPort: 80
    securityContext:
      allowPrivilegeEscalation: true
